AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Parameter0Value:
    Type: String
  Parameter1Value:
    Type: String
  Parameter2Value:
    Type: String
  Parameter3Value:
    Type: String
  Parameter4Value:
    Type: String
  Parameter5Value:
    Type: String
  Parameter6Value:
    Type: String
  Parameter7Value:
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ${Department}-${Project}-${EnvCode}-${System}-${ComponentCode}-${Component}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  BucketPolicy:
    DependsOn:
      - Bucket
Outputs:
  ResourceName:
    Description: The name of the component resource created
    Value: Bucket
    Export:
      Name:
        - ":"
        - - AWS::StackName
          - ResourceName
  ResourceArn:
    Description: The ARN of the component resource created
    Value: Bucket.Arn
    Export:
      Name:
        - ":"
        - - AWS::StackName
          - ResourceArn
